<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.jrebirth</groupId>
		<artifactId>af</artifactId>
		<version>12.0.0-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<groupId>org.jrebirth.af</groupId>
	<artifactId>component</artifactId>
	<packaging>jar</packaging>

	<name>Component</name>
	<description>Convenient JRebirth Components to use with JRAF</description>
	
	<properties>
		<resources.base.path>org/jrebirth/af/component</resources.base.path>
	</properties>
	
	<build>
		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.jrebirth.af</groupId>
							<artifactId>processor</artifactId>
							<version>${project.version}</version>
							<classifier>4ide</classifier>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>api</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
		</dependency>


		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>processor</artifactId>
			<version>${project.version}</version>
			<classifier>4ide</classifier>
			<optional>true</optional>
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>preloader</artifactId>
			<version>${project.version}</version>
			<scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-graphics</artifactId>
		</dependency>

		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- Tests Dependencies (optional TestFX stack tests) - - >
		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
			<classifier>tests</classifier>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testfx</groupId>
			<artifactId>testfx-core</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testfx</groupId>
			<artifactId>testfx-junit</artifactId>
			<scope>test</scope>
		</dependency>-->

	</dependencies>

</project>