/**
 * The class <strong>module-info</strong>. TODO To complete
 * 
 * @author Sébastien Bordes
 */
open module org.jrebirth.af.showcase.undoredo {

    
    requires org.jrebirth.af.api;
    requires org.jrebirth.af.core;
    requires org.jrebirth.af.undoredo;
    
    exports org.jrebirth.af.showcase.undoredo;
    exports org.jrebirth.af.showcase.undoredo.ui;
    exports org.jrebirth.af.showcase.undoredo.command;
    
    // UndoredoModuleStarter is generated by the annotation processor at compile time
    provides org.jrebirth.af.api.module.ModuleStarter with org.jrebirth.af.showcase.undoredo.UndoredoModuleStarter;
}
