/**
 * The module <strong>Workbench ShowCase</strong>.
 * 
 * @author Sébastien Bordes
 */
open module org.jrebirth.af.showcase.workbench {
	
	exports org.jrebirth.af.showcase.workbench;
	exports org.jrebirth.af.showcase.workbench.ui;
	exports org.jrebirth.af.showcase.workbench.resources;

	// WorkbenchModuleStarter is generated by the annotation processor at compile time
	provides org.jrebirth.af.api.module.ModuleStarter with org.jrebirth.af.showcase.workbench.WorkbenchModuleStarter;

	requires javafx.base;
	requires javafx.graphics;

	requires org.jrebirth.af.component;
	requires org.jrebirth.af.core;
}
