<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.jrebirth</groupId>
		<artifactId>af</artifactId>
		<version>9.0.0</version>
		<relativePath>..</relativePath>
	</parent>

	<groupId>org.jrebirth.af</groupId>
	<artifactId>sample</artifactId>
	<packaging>jar</packaging>

	<name>Sample Application</name>
	<url>http://www.sample.org</url>
	<description>Built with JRebirth Framework</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

		<resources.base.path>org/jrebirth/af/sample</resources.base.path>
		<vendor>JRebirth</vendor>
		<appName>JRebirth Sample</appName>
		<archiveName>JRebirthSample</archiveName>
		<exeIcon>src/main/jpackage/JRebirth.ico</exeIcon>
		<mainModule>org.jrebirth.af.sample</mainModule>
		<appClass>org.jrebirth.af.sample.SampleApplication</appClass>
		<appVersion>9.0.0</appVersion>
	</properties>

	<organization>
		<name>JRebirth</name>
		<url>http://www.jrebirth.org</url>
	</organization>

	<build>
		<resources>
			<resource>
				<filtering>false</filtering>
				<directory>${basedir}/src/main/java</directory>
				<includes>
					<include>**/*.fxml</include>
					<include>**/*.properties</include>
					<include>**/*.txt</include>
				</includes>
			</resource>
			<resource>
				<filtering>true</filtering>
				<directory>${basedir}/src/main/resources</directory>
				<targetPath>${resources.base.path}</targetPath>
				<includes>
					<include>**/*.*</include>
				</includes>
				<excludes>
					<exclude>**/*.ttf</exclude>
				</excludes>
			</resource>
			<resource>
				<filtering>false</filtering>
				<directory>${basedir}/src/main/resources</directory>
				<targetPath>${resources.base.path}</targetPath>
				<includes>
					<include>**/*.ttf</include>
				</includes>
			</resource>
		</resources>

		<extensions>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ftp</artifactId>
				<version>2.2</version>
			</extension>
		</extensions>
	</build>

	<dependencies>
		<!-- Use logback logger -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.4.14</version>
			<!--<scope>runtime</scope>-->
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>preloader</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.jrebirth.af</groupId>
			<artifactId>resources</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>

	<profiles>
		<profile>
			<id>APP</id>
			<build>
				<plugins>
<!--					<plugin>
						<groupId>org.openjfx</groupId>
						<artifactId>javafx-maven-plugin</artifactId>
						<version>0.0.5</version>
						<configuration>
							<compress>2</compress>
							<noHeaderFiles>true</noHeaderFiles>
							<stripDebug>true</stripDebug>
							<noManPages>true</noManPages>
							<launcher>${archiveName}</launcher>
							<bindServices>true</bindServices>
							<mainClass>${appClass}</mainClass>
							<jlinkImageName>${archiveName}</jlinkImageName>
							<jlinkZipName>${archiveName}</jlinkZipName>
						</configuration>
										<executions>
							<execution>
								<id>Link-Modules</id>
								<phase>package</phase>
								<goals>
									<goal>jlink</goal>
								</goals>
							</execution>
						</executions>
					</plugin>-->

					<plugin>
						<artifactId>maven-resources-plugin</artifactId>
						<version>3.3.1</version>
						<executions>
							<execution>
								<id>copy-resources</id>
								<!-- here the phase you need -->
								<phase>package</phase>
								<goals>
									<goal>copy-resources</goal>
								</goals>
								<configuration>
									<outputDirectory>
										${project.build.directory}/${archiveName}/conf</outputDirectory>
									<resources>
										<resource>
											<directory>src/main/jpackage</directory>
											<filtering>true</filtering>
										</resource>
									</resources>
								</configuration>
							</execution>
						</executions>
					</plugin>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-dependency-plugin</artifactId>
						<version>3.6.1</version>
						<executions>
							<execution>
								<id>copy</id>
								<phase>package</phase>
								<goals>
									<goal>copy-dependencies</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<includeScope>compile</includeScope>
						</configuration>
					</plugin>

					<plugin>
						<groupId>com.github.akman</groupId>
						<artifactId>jpackage-maven-plugin</artifactId>
						<version>0.1.5</version>
						<dependencies>
							<dependency>
								<groupId>org.ow2.asm</groupId>
								<artifactId>asm</artifactId>
								<version>9.6</version>
							</dependency>
						</dependencies>

						<configuration>

							<addlaunchers>
								<addlauncher>
									<name>launcher1</name>
									<!--<file>config/jpackage/launcher1.properties</file>
    <module>mainModule1Name/mainClass1Name</module>-->
									<!-- <mainjar>mainJar1.jar</mainjar>
    <mainclass>mainClass1Name</mainclass>-->
									<arguments>
										-Dlogback.configurationFile=conf/logback.xml</arguments>
									<javaoptions>-Xms128m -Xmx1024m</javaoptions>
									<!--  <appversion>1.0.1</appversion>-->
									<!--
									<icon>config/jpackage/launcher1.ico</icon>-->
									<winconsole>true</winconsole>
								</addlauncher>
							</addlaunchers>


							<javaoptions>-Dfile.encoding=UTF-8 -Xms256m -Xmx512m</javaoptions>
							<resourcedir>src/main/jpackage</resourcedir>
							<type>EXE</type>
							<dest>target/installer</dest>
							<name>${appName}</name>
							<appversion>${appVersion}</appversion>
							<copyright>Copyright JRebirth 2024</copyright>
							<description>JRebirth Sample Application</description>


							<vendor>${vendor}</vendor>
							<installdir>${vendor}/${appName}</installdir>
							<icon>${exeIcon}</icon>

							<runtimePathOption>MODULEPATH</runtimePathOption>
							<modulepath>
								<pathelements>
									<pathelement>
										${project.build.directory}/${project.groupId}.${project.artifactId}-${project.version}.${project.packaging}</pathelement>
								</pathelements>
								<dependencysets>
									<dependencyset>
										<includeoutput>false</includeoutput>
										<excludeautomatic>false</excludeautomatic>
										<includenames>
											<includename>.*</includename>
										</includenames>
										<excludenames>
											<excludename>javafx\..+Empty</excludename>
										</excludenames>
									</dependencyset>
								</dependencysets>


								<filesets>
									<fileset>
										<directory>
											${project.build.directory}/dependency</directory>
										<excludes>
											<exclude>**/javafx*</exclude>
										</excludes>
										<includes>
											<include>**/javafx*-win.jar</include>
										</includes>
										<followSymlinks>false</followSymlinks>
									</fileset>
								</filesets>
							</modulepath>
							<!--<runtimeimage>target/${archiveName}</runtimeimage>-->


							<module>${mainModule}/${appClass}</module>
							<winmenu>true</winmenu>
							<windirchooser>true</windirchooser>
							<winmenugroup>${vendor}</winmenugroup>
							<winshortcut>true</winshortcut>
							<winconsole>true</winconsole>


						</configuration>
						<executions>
							<execution>
								<id>Package-App</id>
								<phase>install</phase>
								<goals>
									<goal>jpackage</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>
