<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.jrebirth.af</groupId>
		<artifactId>tooling</artifactId>
		<version>12.0.0-SNAPSHOT</version>
		<relativePath>..</relativePath>
	</parent>

	<groupId>org.jrebirth.af.tooling</groupId>
	<artifactId>text2fx</artifactId>
	<name>Text to FX / POJO</name>
	<description>Generate Java POJOs or JavaFX beans from a compact text DSL (.model)</description>

	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-base</artifactId>
		</dependency>
	</dependencies>
</project>
