/**
 * The class <strong>Todos Showcase Module</strong>. 
 * 
 * @author Sébastien Bordes
 */
open module org.jrebirth.af.showcase.todos {

    exports org.jrebirth.af.showcase.todos;
    exports org.jrebirth.af.showcase.todos.ui.main;
    exports org.jrebirth.af.showcase.todos.ui.content;
    exports org.jrebirth.af.showcase.todos.ui.content.list;
    exports org.jrebirth.af.showcase.todos.ui.status;
    exports org.jrebirth.af.showcase.todos.ui.header;
    exports org.jrebirth.af.showcase.todos.ui.content.table;
    exports org.jrebirth.af.showcase.todos.service;
    
    //opens org.jrebirth.af.showcase.todos.ui.header to org.jrebirth.af.core;
    //opens org.jrebirth.af.showcase.todos.ui.main to org.jrebirth.af.core;
    //opens org.jrebirth.af.showcase.todos.ui.content.table to org.jrebirth.af.core;
    //opens org.jrebirth.af.showcase.todos.ui.content.list to org.jrebirth.af.core;
    //opens org.jrebirth.af.showcase.todos.images to org.jrebirth.af.core;

    // TodosModuleStarter is generated by the annotation processor at compile time
    provides org.jrebirth.af.api.module.ModuleStarter with org.jrebirth.af.showcase.todos.TodosModuleStarter;
    
    requires org.jrebirth.af.api;
    requires org.jrebirth.af.core;
    requires org.jrebirth.af.iconfontbridge.fontawesome;
}
