/**
 * The class <strong>Wave Showcase Module</strong>.
 * 
 * @author Sébastien Bordes
 */
open module org.jrebirth.af.showcase.wave {

    
    requires org.jrebirth.af.api;
    requires org.jrebirth.af.core;

    // WaveModuleStarter is generated by the annotation processor at compile time
    provides org.jrebirth.af.api.module.ModuleStarter with org.jrebirth.af.showcase.wave.WaveModuleStarter;
    
//    exports org.jrebirth.af.showcase.wave;
//    exports org.jrebirth.af.showcase.wave.ui;
//    exports org.jrebirth.af.showcase.wave.ui.main;
}
